Repository ljvmiranda921/pyswarms, pull requests merged in 2018-06, with the labels that each got.

#135 Add plotters module
  README.md
  docs/api/_pyswarms.utils.rst
  docs/api/pyswarms.utils.environments.rst
  docs/api/pyswarms.utils.plotters.rst
  docs/assets/inheritance.aux
  docs/assets/inheritance.fdb_latexmk
  docs/assets/inheritance.fls
  docs/assets/optimization_loop.aux
  docs/assets/optimization_loop.fdb_latexmk
  docs/assets/optimization_loop.fls
  docs/assets/pyswarms_api.aux
  docs/assets/pyswarms_api.fdb_latexmk
  docs/assets/pyswarms_api.fls
  docs/examples/output_8_0.png
  docs/examples/output_9_0.png
  docs/examples/visualization.rst
  examples/visualization.ipynb
  pyswarms/base/base_discrete.py
  pyswarms/base/base_single.py
  pyswarms/utils/environments/plot_environment.py
  pyswarms/utils/plotters/__init__.py
  pyswarms/utils/plotters/formatters.py
  pyswarms/utils/plotters/plotters.py
  tests/backend/test_generators.py
  tests/optimizers/test_binary.py
  tests/optimizers/test_global_best.py
  tests/optimizers/test_local_best.py
  tests/utils/environments/conftest.py
  tests/utils/environments/test_plot_environment.py
  tests/utils/plotters/__init__.py
  tests/utils/plotters/conftest.py
  tests/utils/plotters/test_plotters.py
Labels: documentation, enhancement

#137 Format code using black and add pre-commit hooks
  .flake8
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  README.md
  pyproject.toml
  pyswarms/__init__.py
  pyswarms/backend/__init__.py
  pyswarms/backend/generators.py
  pyswarms/backend/operators.py
  pyswarms/backend/swarms.py
  pyswarms/backend/topology/__init__.py
  pyswarms/backend/topology/base.py
  pyswarms/backend/topology/ring.py
  pyswarms/backend/topology/star.py
  pyswarms/base/__init__.py
  pyswarms/base/base_discrete.py
  pyswarms/base/base_single.py
  pyswarms/discrete/__init__.py
  pyswarms/discrete/binary.py
  pyswarms/single/__init__.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
  pyswarms/utils/console_utils.py
  pyswarms/utils/environments/__init__.py
  pyswarms/utils/environments/plot_environment.py
  pyswarms/utils/functions/single_obj.py
  pyswarms/utils/plotters/__init__.py
  pyswarms/utils/plotters/formatters.py
  pyswarms/utils/plotters/plotters.py
  pyswarms/utils/search/__init__.py
  pyswarms/utils/search/base_search.py
  pyswarms/utils/search/grid_search.py
  pyswarms/utils/search/random_search.py
  requirements_dev.txt
  setup.py
  tests/backend/conftest.py
  tests/backend/test_generators.py
  tests/backend/test_operators.py
  tests/backend/topology/conftest.py
  tests/backend/topology/test_ring.py
  tests/backend/topology/test_star.py
  tests/optimizers/conftest.py
  tests/optimizers/test_binary.py
  tests/optimizers/test_global_best.py
  tests/optimizers/test_local_best.py
  tests/utils/environments/conftest.py
  tests/utils/environments/test_plot_environment.py
  tests/utils/functions/conftest.py
  tests/utils/functions/test_singleobj_bounds.py
  tests/utils/functions/test_singleobj_dims.py
  tests/utils/functions/test_singleobj_return.py
  tests/utils/functions/test_singleobj_returndims.py
  tests/utils/plotters/conftest.py
  tests/utils/plotters/test_plotters.py
  tests/utils/search/conftest.py
  tests/utils/search/test_gridsearch.py
  tests/utils/search/test_randomsearch.py
Labels: admin

#141 Created Inverse Kinematics tutorial
  examples/inverse_kinematics.ipynb
Labels: documentation, enhancement, v0.3.0

#144 Feature parameterize obj
  examples/basic_optimization_with_arguments.ipynb
  pyswarms/base/base_discrete.py
  pyswarms/base/base_single.py
  pyswarms/discrete/binary.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
  tests/optimizers/test_objective_func_with_kwargs.py
Labels: enhancement, v0.3.0
