Repository ljvmiranda921/pyswarms, pull requests merged in 2018-07, with the labels that each got.

#151 Create GeneralOptimizer class and fix index error in Pyramid class
  docs/api/pyswarms.single.rst
  docs/api/pyswarms.topology.rst
  pyswarms/__init__.py
  pyswarms/backend/topology/__init__.py
  pyswarms/backend/topology/pyramid.py
  pyswarms/single/__init__.py
  pyswarms/single/general_optimizer.py
  tests/optimizers/conftest.py
  tests/optimizers/test_general_optimizer.py
Labels: documentation, enhancement, v0.3.0

#159 Revert pyyaml version change from 3.12 to 4.1
  requirements_dev.txt
Labels: bug

#155 Add Random topology class
  docs/api/pyswarms.topology.rst
  pyswarms/backend/topology/__init__.py
  pyswarms/backend/topology/pyramid.py
  pyswarms/backend/topology/random.py
  pyswarms/single/general_optimizer.py
  tests/backend/topology/conftest.py
  tests/backend/topology/test_random.py
  tests/optimizers/conftest.py
  tests/optimizers/test_general_optimizer.py
Labels: enhancement, v0.3.0

#164 Add static/dynamic functionality for topologies
  pyswarms/backend/topology/base.py
  pyswarms/backend/topology/pyramid.py
  pyswarms/backend/topology/random.py
  pyswarms/backend/topology/ring.py
  pyswarms/backend/topology/star.py
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/local_best.py
  tests/backend/topology/conftest.py
  tests/backend/topology/test_pyramid.py
  tests/backend/topology/test_random.py
  tests/backend/topology/test_ring.py
  tests/optimizers/conftest.py
  tests/optimizers/test_general_optimizer.py
Labels: enhancement, v0.3.0

#172 Fix plotter module (#167)
  pyswarms/utils/plotters/formatters.py
  pyswarms/utils/plotters/plotters.py
Labels: bug, enhancement, unit tests, v0.3.0

#168 Add objective functions (#158)
  pyswarms/utils/functions/single_obj.py
  tests/utils/functions/conftest.py
  tests/utils/functions/test_singleobj_bounds.py
  tests/utils/functions/test_singleobj_dims.py
  tests/utils/functions/test_singleobj_return.py
  tests/utils/functions/test_singleobj_returndims.py
Labels: enhancement, unit tests, v0.3.0

#176 Fix bug in topology classes
  pyswarms/backend/topology/pyramid.py
  pyswarms/backend/topology/random.py
  pyswarms/backend/topology/ring.py
  tests/backend/topology/conftest.py
  tests/backend/topology/test_pyramid.py
  tests/backend/topology/test_random.py
  tests/backend/topology/test_ring.py
  tests/backend/topology/test_star.py
Labels: bug, v0.3.0

#157 Various documentation updates
  docs/examples/basic_optimization.rst
  docs/examples/inverse_kinematics.rst
  examples/basic_optimization.ipynb
  examples/basic_optimization_with_arguments.ipynb
  examples/inverse_kinematics.ipynb
  pyswarms/backend/generators.py
  pyswarms/backend/operators.py
  pyswarms/backend/swarms.py
  pyswarms/backend/topology/__init__.py
  pyswarms/backend/topology/base.py
  pyswarms/backend/topology/pyramid.py
  pyswarms/backend/topology/random.py
  pyswarms/backend/topology/ring.py
  pyswarms/backend/topology/star.py
  pyswarms/base/base_discrete.py
  pyswarms/base/base_single.py
  pyswarms/discrete/binary.py
  pyswarms/single/__init__.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
  pyswarms/utils/environments/plot_environment.py
  pyswarms/utils/plotters/formatters.py
  pyswarms/utils/plotters/plotters.py
  pyswarms/utils/search/base_search.py
  pyswarms/utils/search/grid_search.py
  pyswarms/utils/search/random_search.py
  tests/backend/topology/conftest.py
  tests/optimizers/test_general_optimizer.py
Labels: documentation, v0.3.0

#186 Fix pyyaml dependency
  requirements_dev.txt
Labels: admin, bug

#181 Update authors list
  AUTHORS.rst
  README.md
Labels: admin, documentation, v0.3.0

#189 Clean up changes for v0.3.0
  pyswarms/backend/topology/pyramid.py
  pyswarms/backend/topology/star.py
  pyswarms/backend/topology/von_neumann.py
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  tests/backend/topology/test_pyramid.py
  tests/backend/topology/test_random.py
  tests/backend/topology/test_ring.py
  tests/backend/topology/test_star.py
  tests/backend/topology/test_von_neumann.py
  tests/optimizers/conftest.py
  tests/optimizers/test_general_optimizer.py
Labels: bug, documentation, enhancement, unit tests, v0.3.0

#188 Update dependencies
  requirements_dev.txt
Labels: admin

#191 Bump version and setup.py
  HISTORY.rst
  pyswarms/__init__.py
  setup.cfg
  setup.py
Labels: admin

#192 Update image source in README
  README.md
Labels: admin
