Repository ljvmiranda921/pyswarms, pull requests merged in 2018-08, with the labels that each got.

#196 Update documentation
  docs/api/_pyswarms.backend.rst
  docs/dev.optimizer.rst
  pyswarms/base/base_single.py
Labels: documentation, v0.3.0

#199 Update features.rst and HISTORY.rst
  HISTORY.rst
  docs/features.rst
Labels: documentation, v0.3.0

#193 Added a Vagrantfile for easier collaboration
  .gitignore
  README.md
  Vagrantfile
  provisioner.sh
Labels: enhancement

#210 Add configuration file for pyup
  pyswarms/utils/.pyup.yml
Labels: admin

#208 Fix docs in ReadTheDocs
  docs/examples/custom_objective_function.rst
  docs/examples/custom_optimization_loop.rst
  docs/examples/inverse_kinematics.rst
  docs/examples/tutorials.rst
  docs/examples/usecases.rst
  docs/examples/visualization.rst
  docs/index.rst
Labels: bug, documentation

#204 Update dependencies via pyup
  requirements_dev.txt
Labels: admin

#218 Update base classes to inherit from ABC
  pyswarms/backend/topology/base.py
  pyswarms/base/base_discrete.py
  pyswarms/base/base_single.py
Labels: admin, enhancement

#217 Remove environments module
  docs/api/_pyswarms.utils.rst
  docs/api/pyswarms.utils.environments.rst
  pyswarms/utils/environments/__init__.py
  pyswarms/utils/environments/plot_environment.py
  tests/utils/environments/__init__.py
  tests/utils/environments/conftest.py
  tests/utils/environments/test_plot_environment.py
Labels: admin

#225 Fix pyup configuration
  .pyup.yml
Labels: admin

#229 Add fmt comments for black
  docs/conf.py
  pyswarms/backend/topology/pyramid.py
  pyswarms/backend/topology/random.py
  pyswarms/backend/topology/ring.py
  pyswarms/backend/topology/star.py
  pyswarms/backend/topology/von_neumann.py
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
  pyswarms/utils/plotters/formatters.py
  tests/backend/topology/conftest.py
  tests/backend/topology/test_pyramid.py
  tests/backend/topology/test_random.py
  tests/backend/topology/test_ring.py
  tests/backend/topology/test_star.py
  tests/backend/topology/test_von_neumann.py
  tests/optimizers/conftest.py
  tests/optimizers/test_general_optimizer.py
  tests/optimizers/test_objective_func_with_kwargs.py
  tests/utils/functions/test_singleobj_bounds.py
  tests/utils/functions/test_singleobj_dims.py
  tests/utils/functions/test_singleobj_return.py
  travis_pypi_setup.py
Labels: bug, unit tests, v.0.4.0

#227 Add reporter module
  docs/api/_pyswarms.utils.rst
  docs/api/pyswarms.utils.reporter.rst
  pyswarms/backend/generators.py
  pyswarms/backend/operators.py
  pyswarms/backend/swarms.py
  pyswarms/backend/topology/base.py
  pyswarms/backend/topology/pyramid.py
  pyswarms/backend/topology/random.py
  pyswarms/backend/topology/ring.py
  pyswarms/backend/topology/star.py
  pyswarms/backend/topology/von_neumann.py
  pyswarms/base/base_discrete.py
  pyswarms/base/base_single.py
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
  pyswarms/utils/__init__.py
  pyswarms/utils/console_utils.py
  pyswarms/utils/functions/single_obj.py
  pyswarms/utils/plotters/formatters.py
  pyswarms/utils/plotters/plotters.py
  pyswarms/utils/reporter/__init__.py
  pyswarms/utils/reporter/reporter.py
  requirements_dev.txt
  setup.py
  tests/optimizers/conftest.py
  tests/optimizers/test_general_optimizer.py
  tests/optimizers/test_global_best.py
  tests/optimizers/test_local_best.py
  tests/optimizers/test_objective_func_with_kwargs.py
Labels: enhancement, v.0.4.0

#226 Add cost function decorator
  docs/api/_pyswarms.utils.rst
  docs/api/pyswarms.utils.decorators.rst
  pyswarms/__init__.py
  pyswarms/utils/decorators/__init__.py
  pyswarms/utils/decorators/decorators.py
  tests/utils/decorators/__init__.py
  tests/utils/decorators/conftest.py
  tests/utils/decorators/test_decorators.py
Labels: documentation, enhancement, unit tests, v.0.4.0

#233 Add stalebot
  .github/stale.yml
Labels: admin

#236 Fix plotters documentation
  README.md
  pyswarms/utils/plotters/formatters.py
  pyswarms/utils/plotters/plotters.py
Labels: documentation
