Repository ljvmiranda921/pyswarms, pull requests merged in 2019-02, with the labels that each got.

#238 Add BoundaryHandler and VelocityHandler
  docs/api/_pyswarms.backend.rst
  docs/api/pyswarms.backend.rst
  docs/api/pyswarms.handlers.rst
  pyswarms/backend/__init__.py
  pyswarms/backend/handlers.py
  pyswarms/backend/operators.py
  pyswarms/backend/topology/pyramid.py
  pyswarms/backend/topology/random.py
  pyswarms/backend/topology/ring.py
  pyswarms/backend/topology/star.py
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
  tests/backend/conftest.py
  tests/backend/test_handlers.py
  tests/backend/test_operators.py
  tests/backend/topology/test_pyramid.py
  tests/backend/topology/test_random.py
  tests/backend/topology/test_ring.py
  tests/backend/topology/test_von_neumann.py
Labels: documentation, enhancement, unit tests, v.0.4.0

#267 Update numpy version
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: admin

#265 Changes made to basic_optimization.ipynb notebook for new API
  examples/basic_optimization.ipynb
  examples/custom_optimization_loop.ipynb
Labels: documentation

#286 Fix handlers
  pyswarms/backend/handlers.py
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
Labels: bug, documentation

#306 Update README
  README.md
Labels: admin, documentation

#304 Removed non-feature "fast" flag from optimizers
  pyswarms/base/base_discrete.py
  pyswarms/base/base_single.py
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
Labels: bug

#305 Update README.md
  README.md
Labels: documentation
