Repository ljvmiranda921/pyswarms, pull requests merged in 2019-04, with the labels that each got.

#312 Support parallel particle evaluation
  pyswarms/backend/operators.py
  pyswarms/base/base_discrete.py
  pyswarms/base/base_single.py
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
  pyswarms/utils/decorators/decorators.py
  tests/optimizers/abc_test_optimizer.py
  tests/optimizers/test_general_optimizer.py
Labels: enhancement

#329 Fix basic optimization example unknown arguments issues
  docs/examples/basic_optimization.rst
  docs/examples/inverse_kinematics.rst
  examples/basic_optimization.ipynb
  examples/inverse_kinematics.ipynb
Labels: documentation

#322 Fix optimise methods returning incorrect best_pos
  pyswarms/discrete/binary.py
  pyswarms/single/general_optimizer.py
  pyswarms/single/global_best.py
  pyswarms/single/local_best.py
  tests/optimizers/test_binary.py
  tests/optimizers/test_general_optimizer.py
  tests/optimizers/test_global_best.py
  tests/optimizers/test_local_best.py
Labels: bug, unit tests
